FROM php:7.4-apache

WORKDIR /var/www/html

COPY index.php .

RUN chown -R www-data:www-data .

RUN chmod -R 774 .

RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql

EXPOSE 80
